// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using probny_kolos_2.Models;

namespace probny_kolos_2.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20200613142826_AddWyrob")]
    partial class AddWyrob
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("probny_kolos_2.Models.Klient", b =>
                {
                    b.Property<int>("IdKlient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlientIdKlient")
                        .HasColumnType("int");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlient");

                    b.HasIndex("KlientIdKlient");

                    b.ToTable("Klients");
                });

            modelBuilder.Entity("probny_kolos_2.Models.WyrobCukierniczy", b =>
                {
                    b.Property<int>("IdWyrobuCukierniczego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CenaZaSzt")
                        .HasColumnType("real");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int?>("WyrobCukierniczyIdWyrobuCukierniczego")
                        .HasColumnType("int");

                    b.HasKey("IdWyrobuCukierniczego");

                    b.HasIndex("WyrobCukierniczyIdWyrobuCukierniczego");

                    b.ToTable("WyrobyCukiernicze");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Klient", b =>
                {
                    b.HasOne("probny_kolos_2.Models.Klient", null)
                        .WithMany("Klients")
                        .HasForeignKey("KlientIdKlient");
                });

            modelBuilder.Entity("probny_kolos_2.Models.WyrobCukierniczy", b =>
                {
                    b.HasOne("probny_kolos_2.Models.WyrobCukierniczy", null)
                        .WithMany("WyrobyCukiernicze")
                        .HasForeignKey("WyrobCukierniczyIdWyrobuCukierniczego");
                });
#pragma warning restore 612, 618
        }
    }
}
