// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using probny_kolos_2.Models;

namespace probny_kolos_2.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("probny_kolos_2.Models.Klient", b =>
                {
                    b.Property<int>("IdKlient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlientIdKlient")
                        .HasColumnType("int");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKlient");

                    b.HasIndex("KlientIdKlient");

                    b.ToTable("Klients");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Pracownik", b =>
                {
                    b.Property<int>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int?>("PracownikIdPracownik")
                        .HasColumnType("int");

                    b.HasKey("IdPracownik");

                    b.HasIndex("PracownikIdPracownik");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("probny_kolos_2.Models.WyrobCukierniczy", b =>
                {
                    b.Property<int>("IdWyrobuCukierniczego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CenaZaSzt")
                        .HasColumnType("real");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int?>("WyrobCukierniczyIdWyrobuCukierniczego")
                        .HasColumnType("int");

                    b.HasKey("IdWyrobuCukierniczego");

                    b.HasIndex("WyrobCukierniczyIdWyrobuCukierniczego");

                    b.ToTable("WyrobyCukiernicze");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Zamow_wyrob", b =>
                {
                    b.Property<int>("IdWyrobuCukierniczego")
                        .HasColumnType("int");

                    b.Property<int>("IdZamowienia")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int?>("Zamow_wyrobIdWyrobuCukierniczego")
                        .HasColumnType("int");

                    b.Property<int?>("Zamow_wyrobIdZamowienia")
                        .HasColumnType("int");

                    b.HasKey("IdWyrobuCukierniczego", "IdZamowienia");

                    b.HasIndex("Zamow_wyrobIdWyrobuCukierniczego", "Zamow_wyrobIdZamowienia");

                    b.ToTable("Zamow_wybory");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Zamowienie", b =>
                {
                    b.Property<int>("IdZamowienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPrzyjecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKlient")
                        .HasColumnType("int");

                    b.Property<int>("IdPracownik")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("IdZamowienia");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Klient", b =>
                {
                    b.HasOne("probny_kolos_2.Models.Klient", null)
                        .WithMany("Klients")
                        .HasForeignKey("KlientIdKlient");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Pracownik", b =>
                {
                    b.HasOne("probny_kolos_2.Models.Pracownik", null)
                        .WithMany("Pracownicy")
                        .HasForeignKey("PracownikIdPracownik");
                });

            modelBuilder.Entity("probny_kolos_2.Models.WyrobCukierniczy", b =>
                {
                    b.HasOne("probny_kolos_2.Models.WyrobCukierniczy", null)
                        .WithMany("WyrobyCukiernicze")
                        .HasForeignKey("WyrobCukierniczyIdWyrobuCukierniczego");
                });

            modelBuilder.Entity("probny_kolos_2.Models.Zamow_wyrob", b =>
                {
                    b.HasOne("probny_kolos_2.Models.Zamow_wyrob", null)
                        .WithMany("Zamow_wyroby")
                        .HasForeignKey("Zamow_wyrobIdWyrobuCukierniczego", "Zamow_wyrobIdZamowienia");
                });
#pragma warning restore 612, 618
        }
    }
}
